# RandomWelcomeRewards Config.yml File

# This file is the heart of the plugin as it configures the listeners for when a player joins your server.
# If you want to edit messages, open up the messages.yml and you can configure any messages availble.
# If you want to add milestones after enabling or disabling them here, go to milestones.yml and follow the directions.
# If you want to change the data for the players (not advised but accessible), go to data.yml and values can be configured.
# After any changes you make to this plugin, remember to reload the plugin or restart your server (if you edited more than one plugin).

# Here is the main part of the plugin, where you can enable or disable the feature available here.
# Enabling newWelcome will allow players to welcome new player :D, same for returnWelcome.
# Enabling milestones will activate what is in the milestones.yml
# Note: if you disable one of the milestones, that particular milestone will not perform.
settings:
  enableNewWelcome: true
  enableReturnWelcome: true
  enableNewWelcomeMilestones: true
  enableReturnWelcomeMilestones: true

   # How much time a player has to welcome the new player (in seconds).
  newTime: 10

  # How much time will it take to be considered a returning player (in minutes).
  returnTimeNeed: 30

  #How much time a player has to welcome back a returning player (in seconds).
  returnTime: 10

   # What you want players to type to trigger the plugin.
  triggeredNewWelcomeTexts:
    - "welcome"
    - "wel"
    - "welcm"

    # What you want players to type to trigger the plugin.
  triggeredReturnWelcomeTexts:
    - "wb"
    - "welcome back"
    - "welback"

# Rewards when welcoming a new player. It will give all the rewards available.
# Use <player> to target the player welcoming the new player if commands is enabled.
newWelcomeRewards:
  vault:
    enable: true
    reward: 100
  commands:
    enable: true
    rewardCommands:
      - "give <player> diamond 1"

returnWelcomeRewards:
  vault:
    enable: true
    reward: 10
  commands:
    enable: false
    rewardCommands:
      - "give <player> diamond 1"

