#RandomWelcomeRewards Config.yml

#Main plugin settings
settings:
  # Enable or disable players to Welcome and/or Welcome Back Players.
  enableNewWelcome: true
  enableReturnWelcome: true

   # How much time a player has to welcome the new player (in seconds).
  newTime: 10

  # How much time will they be considered an returning player to trigger the awards (in minutes).
  returnTimeNeed: 30

  #How much time a player has to welcome back the player (in seconds).
  returnTime: 10

   # What you want players to type to trigger the plugin.
  triggeredNewWelcomeTexts:
    - "welcome"
    - "wel"
    - "welcm"

    # What you want players to type to trigger the plugin.
  triggeredReturnWelcomeTexts:
    - "wb"
    - "welcome back"
    - "welback"
# Rewards when welcoming a new player. It will give all the rewards available.
# Use <player> to target the player welcoming the new player if commands is enabled.
newWelcomeRewards:
  vault:
    enable: true
    reward: 100
  commands:
    enable: true
    rewardCommands:
      - "give <player> diamond 1"

returnWelcomeRewards:
  vault:
    enable: true
    reward: 10
  commands:
    enable: false
    rewardCommands:
      - "give <player> diamond 1"

