name: RandomWelcomeRewards
version: '${project.version}'
main: me.gipper1998.randomwelcomerewards.RandomWelcomeRewards
api-version: 1.18
depend: [ Vault ]
authors: [ gipper1998 ]
description: Generates a random welcome message by the player. This is based off of Ranulls version of welcoming a new player, but adds extra features and vault support.
commands:
  randomwelcomerewards:
    description: Command for all uses
    aliases: [randwelrewards]
permissions:
  randomwelcomerewards.reload:
    description: Reload the plugin
    default: false
  randomwelcomerewards.stats:
    description: Gives the players current record
    default: true
  randomwelcomerewards.stats.others:
    description: See other players records if they are online
    default: false
  randomwelcomerewards.leaderboards.newwelcomes:
    description: Check the leaderboards for new welcomes.
    default: true
  randomwelcomerewards.leaderboards.returnwelcomes:
    description: Check the leaderboards for return welcomes.
    default: true
